import { test, expect } from '@playwright/test';
import { movies, filters, matchesFilter } from '../src/movies';
test('all film choices, filters, persistence and sharing',async({page,context})=>{
 test.setTimeout(90000);await page.emulateMedia({reducedMotion:'reduce'});
 await context.grantPermissions(['clipboard-read','clipboard-write']);
 await page.goto('/');
 for(const f of filters){await page.getByRole('button',{name:f,exact:true}).click();await expect(page.locator('.movie-card')).toHaveCount(movies.filter(m=>matchesFilter(m,f)).length);}
 await page.getByRole('button',{name:'All',exact:true}).click();
 for(const m of movies){const card=page.locator('.movie-card').filter({has:page.getByRole('heading',{name:m.title,exact:true})});await card.getByText('The little details').click();await expect(card.locator('.reason')).toHaveText(m.why);await card.getByRole('button',{name:'Pick this one'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Yep, this one'}).click();await expect(page.locator('.result h3')).toHaveText(m.title);await page.getByRole('button',{name:'Change my choice'}).click();}
 await page.locator('.movie-card').first().getByRole('button',{name:'Pick this one'}).click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();
 await page.locator('.movie-card').first().getByRole('button',{name:'Pick this one'}).click();await page.getByRole('button',{name:'Yep, this one'}).click();await page.reload();await expect(page.locator('.result h3')).toHaveText(movies[0].title);
 await page.getByRole('button',{name:'I genuinely cannot choose.'}).click();await expect(page.getByRole('button',{name:'Accept fate'})).toBeVisible({timeout:5000});await page.getByRole('button',{name:'Accept fate'}).click();await expect(page.getByRole('dialog')).toBeVisible();
});
for(const width of [375,430,768,1440])test(`layout at ${width}`,async({page})=>{await page.setViewportSize({width,height:900});await page.goto('/');await page.evaluate(()=>document.fonts.ready);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/layout-${width}.png`,fullPage:true});});
test('reduced motion and keyboard focus',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');expect(await page.locator('.lilies').evaluateAll(els=>els.every(el=>getComputedStyle(el).animationName==='none'))).toBe(true);await page.locator('.movie-card').first().getByRole('button',{name:'Pick this one'}).click();for(let i=0;i<6;i++){await page.keyboard.press('Tab');expect(await page.evaluate(()=>!!document.activeElement?.closest('dialog'))).toBe(true);}});
test('all original poster artwork loads',async({page})=>{await page.goto('/');for(const card of await page.locator('.movie-card').all()){const poster=card.locator('.poster img');await poster.scrollIntoViewIfNeeded();await expect(poster).toBeVisible();await expect.poll(()=>poster.evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);}await expect(page.locator('.movie-card .title-art')).toHaveCount(0);});

test('WhatsApp shares poster file and message',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('twinkle-choice','notting-hill');Object.defineProperty(navigator,'canShare',{value:()=>true});Object.defineProperty(navigator,'share',{value:async(data:ShareData)=>{(window as any).shared={text:data.text,name:data.files?.[0].name,size:data.files?.[0].size,type:data.files?.[0].type}}});});await page.goto('/');await page.getByRole('button',{name:'It’s a date — tell him on WhatsApp ♡'}).click();const shared=await page.evaluate(()=>(window as any).shared);expect(shared.text).toContain('I picked Notting Hill');expect(shared.name).toBe('notting-hill.jpg');expect(shared.size).toBeGreaterThan(1000);expect(shared.type).toBe('image/jpeg');await expect(page.getByRole('button',{name:'Copy choice'})).toHaveCount(0);
});
test('WhatsApp fallback downloads poster and opens recipient',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('twinkle-choice','the-holiday');Object.defineProperty(navigator,'canShare',{value:()=>false});window.open=((url:string)=>{(window as any).whatsappUrl=url;return null}) as typeof window.open;});await page.goto('/');const download=page.waitForEvent('download');await page.getByRole('button',{name:'It’s a date — tell him on WhatsApp ♡'}).click();expect((await download).suggestedFilename()).toBe('the-holiday.jpg');expect(await page.evaluate(()=>(window as any).whatsappUrl)).toMatch(/^https:\/\/wa\.me\/918433937459\?text=I%20picked%20The%20Holiday/);await expect(page.getByRole('status').filter({hasText:'Poster downloaded'})).toBeVisible();
});
