import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUpRight, Check, Heart, Shuffle, X, Sparkles } from 'lucide-react';
import { movies, filters, matchesFilter, type Movie } from './movies';

function scrollToElement(el: HTMLElement | null) { el?.scrollIntoView({behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block:'start'}); }
function Poster({movie, priority=false}: {movie:Movie; priority?:boolean}) {
 const [failed,setFailed]=useState(false);
 return <div className="poster" style={{background:movie.color}}>{movie.posterUrl && !failed ? <img src={movie.posterUrl} alt={`Official poster for ${movie.title} (${movie.year})`} loading={priority?'eager':'lazy'} onError={()=>setFailed(true)}/> : <div className="title-art" role="img" aria-label={`${movie.title}, ${movie.year} — illustrated title panel, official poster not yet added`}><span className="art-top">A LITTLE ROMANCE · {movie.year}</span><span className="art-star">✦</span><strong>{movie.title}</strong><span className="art-line"/><span className="art-bottom">ONE EVENING. TWO OF US.</span></div>}</div>
}
function LilyDecoration({className=''}:{className?:string}) {return <img className={`lilies ${className}`} src="./lily-sticker.png" alt="" aria-hidden="true"/>}
function ThinkingPhoto({caption,className=''}:{caption:string;className?:string}) {return <figure className={`thinking-photo ${className}`}><img src="./twinkle-thinking.png" alt="Twinkle striking a thoughtful pose" width="1024" height="1536" loading="lazy"/><figcaption>{caption}</figcaption></figure>}
function MovieCard({movie,onPick}:{movie:Movie;onPick:(m:Movie)=>void}) {return <article className="movie-card"><div className="poster-wrap"><Poster movie={movie}/><span className="runtime">{movie.runtime} min</span></div><div className="card-heading"><h3>{movie.title}</h3><span>{movie.year}</span></div><div className="tags">{movie.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><p className="short-description">{movie.short}</p><details><summary>The little details <span>+</span></summary><p>{movie.description}</p><p className="reason">{movie.why}</p>{movie.tags.includes('Emotional')&&<small>Potential crying ahead.</small>}{(movie.tags.includes('Yearning')||movie.tags.includes('Classic Romance'))&&<small>Professional-grade yearning.</small>}</details><button className="pick-button" onClick={()=>onPick(movie)}>Pick this one <Heart size={15}/></button></article>}
function MovieSelectionModal({movie,onClose,onConfirm}:{movie:Movie|null;onClose:()=>void;onConfirm:(m:Movie)=>void}) {
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(movie) ref.current?.showModal();else ref.current?.close()},[movie]);
 return <dialog ref={ref} aria-labelledby="modal-title" onKeyDown={e=>{if(e.key==='Tab'){const buttons=ref.current?.querySelectorAll<HTMLButtonElement>('button');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><button className="close" aria-label="Close confirmation" onClick={onClose}><X size={20}/></button>{movie&&<><LilyDecoration className="modal-lily"/><span className="eyebrow">A VERY GOOD POSSIBILITY</span><div className="decision-duo"><div className="modal-poster"><Poster movie={movie}/></div><ThinkingPhoto className="thinking-mini" caption="Hmm… this one?"/></div><h2 id="modal-title">So… {movie.title}?</h2><p>Just us, this movie, and something good to snack on.</p><p className="lock">Lock it in?</p><button className="primary" onClick={()=>onConfirm(movie)}>Yep, this one ♡</button><button className="text-button" onClick={onClose}>Wait, let me reconsider</button></>}</dialog>
}
function ShareChoice({movie,onChange}:{movie:Movie;onChange:()=>void}) {
 const [notice,setNotice]=useState('');const [poster,setPoster]=useState<File|null>(null);const [loading,setLoading]=useState(true);const [sharing,setSharing]=useState(false);
 const message=`I picked ${movie.title} for our movie night 🤍\nSo when are we watching it?`;
 useEffect(()=>{let active=true;setPoster(null);setLoading(true);setNotice('');fetch(movie.posterUrl).then(r=>{if(!r.ok)throw new Error('Poster unavailable');return r.blob()}).then(blob=>{if(active)setPoster(new File([blob],movie.id+(blob.type==='image/png'?'.png':'.jpg'),{type:blob.type||'image/jpeg'}))}).catch(()=>{if(active)setNotice('The poster could not load. You can still send your movie choice.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[movie]);
 const canSharePoster=!!poster&&!!navigator.share&&!!navigator.canShare?.({files:[poster]});
 async function share(){
  if(canSharePoster&&poster){setSharing(true);try{await navigator.share({files:[poster],text:message,title:'Our movie night'});setNotice('Finish sending in WhatsApp ♡');}catch(error){if((error as Error).name!=='AbortError')setNotice('Sharing didn’t open. Please tap WhatsApp to try again.');}finally{setSharing(false)}return;}
  if(poster){const url=URL.createObjectURL(poster);const link=document.createElement('a');link.href=url;link.download=poster.name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  window.open(`https://wa.me/918433937459?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');
  setNotice(poster?'Poster downloaded. Attach it in our WhatsApp chat, then tap Send.':'Your WhatsApp chat is opening with the movie choice.');
 }
 return <div className="share-choice"><div className="romantic-share"><LilyDecoration className="share-lily share-lily-left"/><button className="primary" disabled={loading||sharing} onClick={share}>{loading?'Preparing the poster…':sharing?'Opening share sheet…':'It’s a date — tell him on WhatsApp ♡'} <ArrowUpRight size={17}/></button><LilyDecoration className="share-lily share-lily-right"/></div><p className="notice" role="status">{notice}</p><button className="text-button" onClick={onChange}>Change my choice</button></div>
}
function RandomMoviePicker({onPick}:{onPick:(m:Movie)=>void}) {
 const [movie,setMovie]=useState<Movie|null>(null);const [spinning,setSpinning]=useState(false);const timer=useRef<ReturnType<typeof setInterval>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearInterval(timer.current)},[]);
 function spin(){if(spinning)return;setSpinning(true);let count=0;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches; const chosen=movies[Math.floor(Math.random()*movies.length)];timer.current=setInterval(()=>{count++;setMovie(movies[Math.floor(Math.random()*movies.length)]);if(count>=(reduced?1:15)){clearInterval(timer.current!);timer.current=null;setMovie(chosen);setSpinning(false)}},130)}
 return <section id="fate" className="fate-section"><LilyDecoration className="section-lily fate-lily"/><div className="fate-copy"><ThinkingPhoto className="thinking-fate" caption="Me, still deciding…"/><span className="eyebrow">A LITTLE HELP FROM THE UNIVERSE</span><h2>Still can’t <em>choose?</em></h2><p>Leaving our movie night to fate seems responsible.</p><button className="primary" onClick={spin} disabled={spinning}><Shuffle size={17}/>{spinning?'Consulting the universe…':movie?'Absolutely not, spin again':'I genuinely cannot choose.'}</button></div><div className={`fate-card ${spinning?'shuffling':''}`}><span className="fate-star" aria-hidden="true">✦</span>{movie?<><div className="fate-poster"><Poster movie={movie}/></div><div aria-live="polite">{!spinning&&<><span className="eyebrow">THE UNIVERSE HAS SPOKEN…</span><h3>{movie.title}</h3><button className="text-button" onClick={()=>onPick(movie)}>Accept fate ♡</button></>}</div></>:<><span className="fate-number">{movies.length} films. One little nudge.</span><p>Some things are<br/><em>better left to fate.</em></p></>}</div></section>
}
export default function App(){
 const [filter,setFilter]=useState('All');const [pending,setPending]=useState<Movie|null>(null);const [chosen,setChosen]=useState<Movie|null>(()=>{try{return movies.find(m=>m.id===localStorage.getItem('twinkle-choice'))||null}catch{return null}});const [secret,setSecret]=useState(false);const resultRef=useRef<HTMLElement>(null);
 const [shortlist]=useState(()=>[...movies].sort(()=>Math.random()-.5).slice(0,5));
 function confirm(m:Movie){setChosen(m);setPending(null);try{localStorage.setItem('twinkle-choice',m.id)}catch{}setTimeout(()=>scrollToElement(resultRef.current),70)}
 function change(){setChosen(null);try{localStorage.removeItem('twinkle-choice')}catch{}setTimeout(()=>scrollToElement(document.getElementById('movies')),20)}
 useEffect(()=>{
 const context=(document as Document & {modelContext?: {registerTool: (tool:unknown, options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(!context?.registerTool)return;const lifecycle=new AbortController();
 const tool={name:'stage_movie_choice',description:'Open the confirmation dialog for a movie. Does not confirm or share the choice.',inputSchema:{type:'object',properties:{movieId:{type:'string',enum:movies.map(m=>m.id)}},required:['movieId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const id=(input as {movieId?:unknown})?.movieId;const movie=movies.find(m=>m.id===id);if(!movie)throw new Error('Unknown movie ID');setPending(movie);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {movieId:movie.id,status:'awaiting_confirmation'};}};
 try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return ()=>lifecycle.abort();
 },[]);
 const visible=movies.filter(m=>matchesFilter(m,filter));
 return <><a className="skip-link" href="#movies">Skip to movies</a><header><a className="wordmark" href="#">Twinkle</a><button className="secret-button" aria-label="A little star" onClick={()=>{setSecret(true);setTimeout(()=>setSecret(false),4500)}}>✦</button><span className="nav-label">MOVIE NIGHT</span><nav aria-label="Main navigation"><a href="#movies">The movies</a><a href="#fate">Pick for me <Shuffle size={13}/></a></nav>{secret&&<div className="secret" role="status">The company was the easy choice. ♡</div>}</header><main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="little-line"/> AN INVITATION FOR TWO</div><h1>Twinkle,<br/>what are we<br/><em>watching?</em></h1><p>I did the difficult part and found the movies.<br className="desktop-break"/> You just have to pick one.</p><a href="#movies" className="primary">Show me the movies <ArrowDown size={17}/></a><span className="hero-note">You pick the movie. I’ll bring the snacks.</span><figure className="spotify-card"><figcaption><strong>Scan me ♡</strong><span>A little soundtrack while you decide.</span></figcaption><img src="./spotify-code.jpg" width="684" height="180" alt="Spotify code to scan in the Spotify app"/><p>Scan with Spotify, or save this image and open it in Spotify’s scanner.</p><a href="./spotify-code.jpg" download="a-little-soundtrack.jpg">Save code image ↗</a></figure></div><div className="hero-art"><span className="flower-stamp">FLOWERS FIRST.<br/>MOVIE SECOND. ♡</span><LilyDecoration/><div className="bouquet-note">a few flowers,<br/><em>while you decide.</em><span>♡</span></div></div><div className="hero-bottom"><span>A LITTLE ROMANCE. A VERY IMPORTANT DECISION.</span><span>SCROLL TO FALL IN LOVE <ArrowDown size={12}/></span></div></section><div className="love-strip" aria-hidden="true"><span>YOU + ME + A GOOD MOVIE</span><span>✦</span><span>A LITTLE ROM-COM ENERGY</span><span>✦</span><span>YOU + ME + A GOOD MOVIE</span></div>
 {chosen&&<section ref={resultRef} className="result" id="our-movie"><LilyDecoration className="section-lily result-lily"/><span className="celebration" aria-hidden="true">✦ ♡ ✧</span><span className="eyebrow"><Check size={14}/> IT’S A DATE</span><h2>Movie night is<br/><em>officially decided.</em></h2><div className="result-poster"><Poster movie={chosen}/></div><h3>{chosen.title}</h3><div className="tags">{chosen.tags.map(t=><span key={t}>{t}</span>)}</div><p>Excellent choice, Twinkle. I’ll handle the snacks.</p><ShareChoice movie={chosen} onChange={change}/></section>}
 <section className="shortlist section-shell"><LilyDecoration className="section-lily shortlist-lily"/><div className="section-top"><div><span className="eyebrow">IF YOU NEED A STARTING POINT</span><h2>Tonight’s <em>shortlist.</em></h2></div><span className="small-note">A few possibilities. No pressure.</span></div><div className="shortlist-track">{shortlist.map((m,i)=><button key={m.id} className="shortlist-item" onClick={()=>setPending(m)} aria-label={`Consider ${m.title}`}><Poster movie={m}/><span className="shortlist-caption"><span>0{i+1}</span>{m.title}<ArrowUpRight size={14}/></span></button>)}</div></section>
 <section id="movies" className="collection section-shell"><LilyDecoration className="section-lily collection-lily"/><div className="section-top"><div><span className="eyebrow">THE CURATED COLLECTION</span><h2>A movie for <em>our kind of night.</em></h2></div><span className="collection-count">{movies.length} films, one lucky winner.</span></div><div className="collection-intro"><p className="collection-note">There are no wrong answers. There may, however, be questionable ones.</p><ThinkingPhoto className="thinking-collection" caption="A very serious film critic. ♡"/></div><div className="filters" aria-label="Filter movies by mood">{filters.map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div>{filter==='Flirty'&&<p className="collection-note">Some of these are less ‘cute bookstore romance’ and more ‘this seemed like a good idea at the time.’</p>}<div className="collection-label"><span>{filter==='All'?'ALL THE POSSIBILITIES':filter.toUpperCase()}</span><span aria-live="polite">{visible.length} FILMS</span></div><div className="movie-grid" key={filter}>{visible.map(m=><MovieCard key={m.id} movie={m} onPick={setPending}/>)}</div></section><RandomMoviePicker onPick={setPending}/></main><footer><LilyDecoration className="footer-lily"/><Sparkles size={20}/><p>Made for Twinkle <span>✦</span></p><small>One very serious movie decision at a time.</small></footer><MovieSelectionModal movie={pending} onClose={()=>setPending(null)} onConfirm={confirm}/></>
}
